backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: "Title", name: "title", widget: "string"}
